Update dependencies doing incorrectly nightly version detection
Old versions of ahash and proc-macro2 were making assumptions about
nightly features that are not true on new nightly versions of rustc:
```
error[E0635]: unknown feature `stdsimd`
  --> /home/jyn/.local/lib/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ahash-0.8.6/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
error[E0635]: unknown feature `stdsimd`
  --> /home/jyn/.local/lib/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ahash-0.7.6/src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
error[E0635]: unknown feature `proc_macro_span_shrink`
  --> /home/jyn/.local/lib/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proc-macro2-1.0.50/src/lib.rs:92:30
   |
92 |     feature(proc_macro_span, proc_macro_span_shrink)
   |                              ^^^^^^^^^^^^^^^^^^^^^^
```

Fix them by updating to a newer version.

This commit can be replicated using `cargo update proc-macro2 ahash@0.8.2 ahash@0.7.6 quote once_cell`.